services:
  db:
    image: public.ecr.aws/docker/library/mysql:8.2.0
    environment:
      - "MYSQL_ROOT_PASSWORD=Welcome#1234"
    networks:
      - django-nginx

  backend:
    build:
      context: ./backend
    command: /start_prod.sh
    environment:
      - "DJANGO_DEBUG=False"
    networks:
      - django-nginx
    volumes:
      - .:/code
      - django-static:/backend/static
    ports:
      - "8003:8003"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - django-nginx
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    depends_on:
      - backend
    environment:
      - LOG_LEVEL=debug

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    ports:
      - "8002:8002"
    depends_on:
      - backend
    networks:
      - django-nginx
    environment:
      - NODE_ENV=build
      - LOG_LEVEL=debug


volumes:
  django-static:

networks:
  django-nginx:
    driver: bridge
